name: sepm

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: recruiting
      POSTGRES_USER: recruiting
      POSTGRES_PASSWORD: recruiting
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recruiting -d recruiting"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: mkafri/sepm-backend:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/recruiting
      SPRING_DATASOURCE_USERNAME: recruiting
      SPRING_DATASOURCE_PASSWORD: recruiting

      APP_STORAGE_BASE_PATH: /data/resumes
    volumes:
      - ./backend/data/resumes:/data/resumes
    restart: unless-stopped

  web:
    image: mkafri/sepm-frontend:latest
    ports:
      - "8085:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
